automation: #Автоматизации
  ##############

  ####
  - alias: "btnClick (hall_btn01)" # при клике на кнопку переключает настольную лампу
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/hall_btn01
    condition:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'single' }}"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.hall_socketx4_01_l5

  ####
  - alias: "Ночник (hall_socketx4_01_l5) - автовыключение через 20 мин"
    trigger:
      - platform: state
        entity_id: switch.hall_socketx4_01_l5
    mode: restart
    action:
      - if:
          - condition: state
            entity_id: switch.hall_socketx4_01_l5
            state: "on"
        then:
          - delay: "00:20:00"
          - service: switch.turn_off
            target:
              entity_id: switch.hall_socketx4_01_l5

  ####
  - alias: "Климат в зале - Управление при открытии/закрытии окна"
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_sensor05_contact
        to: "on"
        for:
          minutes: 1
        id: "window_open"
      - platform: state
        entity_id: binary_sensor.hall_sensor05_contact
        to: "off"
        for:
          minutes: 1
        id: "window_closed"
    action:
      - choose:
          - conditions: "{{ trigger.id == 'window_open' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: climate.gostinaia
                data:
                  hvac_mode: "off"
          - conditions: "{{ trigger.id == 'window_closed' }}"
            sequence:
              - service: climate.set_hvac_mode
                target:
                  entity_id: climate.gostinaia
                data:
                  hvac_mode: "heat"

  ####
  - alias: "turnoff_battery_light_when_central_light_turnedon" # выкачаем свет батареи и ночник когда включён основной свет
    trigger:
      platform: state
      entity_id:
        - switch.hall_switch01_left # центральный свет (левый)
        - switch.hall_switch01_center # центральный свет (центр)
      to: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.hall_socketx4_01_l2
            - switch.hall_socketx4_01_l5

  ####
  # ОБНОВЛЕНО: Теперь эта автоматизация делает две вещи:
  # 1. Выключает основной свет.
  # 2. Выключает "соседний" фоновый свет (взаимное исключение).
  - alias: "Режим фонового света (Взаимное исключение)"
    trigger:
      - platform: state
        entity_id: switch.hall_socketx4_01_l2 # Свет батареи
        to: "on"
        id: "battery_light"
      - platform: state
        entity_id: switch.hall_socketx4_01_l5 # Ночник
        to: "on"
        id: "night_light"
    action:
      # 1. Всегда выключаем основной свет, так как перешли в "уютный режим"
      - service: switch.turn_off
        target:
          entity_id:
            - switch.hall_switch01_left
            - switch.hall_switch01_center

      # 2. Взаимное исключение: выключаем тот фоновый свет, который НЕ был триггером
      - choose:
          # Если включили Батарею -> Выключаем Ночник
          - conditions: "{{ trigger.id == 'battery_light' }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.hall_socketx4_01_l5

          # Если включили Ночник -> Выключаем Батарею
          - conditions: "{{ trigger.id == 'night_light' }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.hall_socketx4_01_l2

  ####
  - alias: "switchRadiatorLight" #Переключаем подсветку батареи при нажатии правой кнопки выключателя
    trigger:
      platform: state
      entity_id: switch.hall_switch01_right
      to: "on"
    action:
      - service: switch.toggle
        target:
          entity_id:
            - switch.hall_socketx4_01_l2
      - delay: 1
      - service: switch.turn_off
        target:
          entity_id: switch.hall_switch01_right

  ####
  - alias: "Беспроводная кнопка в зале"
    trigger:
      - platform: mqtt
        topic: zigbee2mqtt/hall_btn02
    action:
      - choose:
          # Кнопка 1
          - conditions: "{{ trigger.payload_json.action == '1_single' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.hall_switch01_left
          # Кнопка 2
          - conditions: "{{ trigger.payload_json.action == '2_single' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.hall_switch01_center
          # Кнопка 3
          - conditions: "{{ trigger.payload_json.action == '3_single' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.hall_socketx4_01_l5
          # Кнопка 4
          - conditions: "{{ trigger.payload_json.action == '4_single' }}"
            sequence:
              - service: switch.toggle
                target:
                  entity_id: switch.hall_socketx4_01_l2

  ####
  - alias: "Управление шторами при включении света в зале"
    trigger:
      - platform: state
        entity_id:
          - switch.hall_switch01_left
          - switch.hall_switch01_center
        to: "on"
    action:
      - service: "cover.{{ 'close_cover' if is_state('sun.sun', 'below_horizon') else 'open_cover' }}"
        target:
          entity_id: cover.0x842712fffeba18f7
