generic_hygrostat:
  - name: Увлажнитель в зале
    humidifier: switch.hall_socketx4_01_l4
    target_sensor: sensor.hall_humidity
    min_humidity: 35
    max_humidity: 65
    target_humidity: 50
    device_class: "humidifier"
    min_cycle_duration:
      seconds: 180
    keep_alive:
      minutes: 30

  - name: Увлажнитель в спальне
    humidifier: switch.bedroom_socketx4_01_l1
    target_sensor: sensor.vlazhnost_v_spalne
    min_humidity: 35
    max_humidity: 65
    target_humidity: 50
    device_class: "humidifier"
    min_cycle_duration:
      seconds: 180
    keep_alive:
      minutes: 30

automation:
  - alias: "Smart Humidity Target"
    trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: state
        entity_id: sensor.street_sensor02_temperature
        for: "00:10:00"
    action:
      - service: humidifier.set_humidity
        target:
          entity_id:
            - humidifier.uvlazhnitel_v_spalne
            - humidifier.uvlazhnitel_v_zale
        data:
          humidity: >-
            {% set t_out = states('sensor.street_sensor02_temperature')|float(0) %}
            {# Ограничиваем диапазон от -20 до +30 #}
            {% set t_clamped = ([ -20, t_out, 30 ]|sort)[1] %}
            {# Формула: чем холоднее, тем ниже влажность (чтобы окна не плакали) #}
            {{ ((t_clamped + 20)*0.2 + 40) | int }}

  ####
  - alias: "Humidifier Master Control"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.semia_doma
          - binary_sensor.open_windows
          - binary_sensor.den
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.semia_doma
                state: "on"
              - condition: state
                entity_id: binary_sensor.open_windows
                state: "off"
              - condition: state
                entity_id: binary_sensor.den
                state: "on"
            sequence:
              - service: humidifier.turn_on
                target:
                  entity_id:
                    - humidifier.uvlazhnitel_v_spalne
                    - humidifier.uvlazhnitel_v_zale

        default:
          - service: humidifier.turn_off
            target:
              entity_id:
                - humidifier.uvlazhnitel_v_spalne
                - humidifier.uvlazhnitel_v_zale
