##############
automation: #Автоматизации
  ##############

  ####
  - id: "rightButtonLEDstrip"
    alias: "rightButtonLEDstrip"
    mode: single
    trigger:
      platform: state
      entity_id: switch.loggia_switch01_right
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.loggia_switch01_right
                state: "on"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.wled
              - service: timer.cancel
                target:
                  entity_id: timer.move_led
          - conditions:
              - condition: state
                entity_id: switch.loggia_switch01_right
                state: "off"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.wled

  ####
  - id: "workplaceIlluminationLoggia"
    alias: "workplaceIlluminationLoggia"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.podsvetka_rab_mesta
    action:
      - service: "light.turn_{{ trigger.to_state.state }}"
        target:
          entity_id: light.workplaceIllumination
